trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'
# demo 
jobs:
  - job:
    displayName: 'Spectral Job'
    steps:
      - script: curl -L 'https://spectral-eu.checkpoint.com/latest/x/sh?dsn=$(SPECTRAL_DSN)' | sh
        displayName: 'Install Spectral'

      - script: $HOME/.spectral/spectral scan --ok --dsn $(SPECTRAL_DSN)
        displayName: 'Spectral Scan'